# Model
model:
  name: "dual_swinmae_s"
  params:
    norm_pix_loss: False
    target_type: "origin"
    
train:
  experiment_name: "mae"
  # Runner
  num_epochs: 4000
  start_saving_epoch: 1000
  saving_interval: 40
  max_iter: ~
  log_iter: ~
  eval_iter: ~
  runner_name: mae
  distributed: False
  device: cuda
  resume: output_dir/dual_swin_small_unnormalized_target_origin/checkpoint-1040.pth

  # Dataloader
  batch_size: 32
  num_workers: 4
  drop_last: True

  # Hyperparameter
  mask_ratio: 0.75
  accum_iter: 4
  warmup_epochs: 40
  lr: 1.5e-04
  min_lr: 1.0e-05
  weight_decay: 0.01

  # Dataset
  dataset:
    name: "sunrgbd"
    params:
      root: "data/sunrgbd_trainval"
      split: "train"
    common_transforms:
      RandomResizedCrop:
        params:
          size: [224, 224]
          scale: [0.2, 1.0]
          interp_mode: 3
      RandomHorizontalFlip:
        params: ~
      to_tensor:
        params: ~

    transforms:
      normalize:
        params:
          # sunrgbd rgb
          mean: [0.4960, 0.4686, 0.4415]
          std: [0.2781, 0.2865, 0.2917]
          # nyuv2
          # mean: [0.4184, 0.3545, 0.3333]
          # std: [0.2993, 0.2884, 0.2945]
    depth_transforms:
      normalize:
        params:
          # sunrgbd depth
          mean: [0.4132, 0.4132, 0.4132]
          std: [0.2703, 0.2703, 0.2703]

    target_transforms:
      normalize:
        params:
          # sunrgbd depth
          mean: [0.4975, 0.4975, 0.4975]
          std: [0.2218, 0.2218, 0.2218]


  # Losses
  losses:
    ~

  # Optimizer
  opt_params:
    lr_default: 1.5e-04
    wd_default: 0.01
    betas: (0.9, 0.95)
    momentum: ~
    lr_list: ~
    group_keys: ~
    wd_list: ~

  opt_name: "adamw"
  scheduler_name: "constant"
  # Logger
  use_tensorboard: True
  tensorboard_folder:
  log_dir: log/dual_swin_small_unnormalized_target_origin
  output_dir: output_dir/dual_swin_small_unnormalized_target_origin
  model_folder: ~
