# Model
model:
  name: "encoder_decoder"
  params:
    backbone:
      name: "swin_s"
      params: 
        frozen_stages: -1
    decoder:
      name: "mlp"
      params:
        in_channels: [96, 192, 384, 768]
    aux_head: ~
    norm_layer: "BatchNorm2d"
    pretrained: output_dir/dual_swin_small_normalized_target_origin/checkpoint-1080.pth
    train_cfg:
      bn_eps: 1e-3
      bn_momentum: 0.1

train:
  experiment_name: "semseg"
  # Runner
  runner_name: semseg
  distributed: False
  device: cuda
  resume: ~

  # Train config
  batch_size: 32
  num_workers: 4
  drop_last: True
  lr: 6e-5
  lr_power: 0.9
  momentum: 0.9
  weight_decay: 0.01
  num_epochs: 500
  warmup_epochs: 10
  train_scale_array: [0.5, 0.75, 1, 1.25, 1.5, 1.75]


  # Dataset
  dataset:
    name: "sunrgbd"
    params:
      root: "data/sunrgbd_trainval"
      split: "train"
    common_transforms:
      RandomResizedCrop:
        params:
          size: [224, 224]
          scale: [0.2, 1.0]
          interp_mode: 3
      RandomHorizontalFlip:
        params: ~
      to_tensor:
        params: ~

    transforms:
      normalize:
        params:
          # sunrgbd rgb
          mean: [0.4960, 0.4686, 0.4415]
          std: [0.2781, 0.2865, 0.2917]
          # nyuv2
          # mean: [0.4184, 0.3545, 0.3333]
          # std: [0.2993, 0.2884, 0.2945]
    depth_transforms:
      normalize:
        params:
          # sunrgbd depth
          mean: [0.4132, 0.4132, 0.4132]
          std: [0.2703, 0.2703, 0.2703]

    target_transforms:
      normalize:
        params:
          # sunrgbd depth anything
          mean: [0.4975, 0.4975, 0.4975]
          std: [0.2218, 0.2218, 0.2218]

  # Losses
  losses:
    ~

  # Optimizer
  opt_params:
    lr_default: 1.5e-04
    wd_default: 0.01
    betas: (0.9, 0.95)
    momentum: ~
    lr_list: ~
    group_keys: ~
    wd_list: ~

  opt_name: "adamw"
  scheduler_name: "constant"
  # Logger
  use_tensorboard: True
  tensorboard_folder:
  log_dir: log/semseg/dual_swin_small_normalized_target_origin
  output_dir: output_dir/semseg/dual_swin_small_normalized_target_origin
  model_folder: ~

val:
  # Dataset
  dataset: ~
test:
  need_test: False
