# Dataloader
batch_size: 1
num_workers: 4
drop_last: True
# Dataset
dataset:
  name: "nyuv2"
  params:
    root: "data/NYUDepthv2"
    split: "train"
  common_transforms: ~
  transforms:
    to_tensor:
      params: ~
  depth_transforms:
    to_tensor:
      params: ~
  target_transforms:
    to_tensor:
      params: ~
  label_transforms: ~