# Dataloader
batch_size: 64
num_workers: 4
drop_last: True
# Dataset
dataset:
  name: "sunrgbd"
  params:
    root: "data/sunrgbd/sunrgbd_trainval"
    split: "train"
  transforms:
    # crop_border:
    #   params:
    #     width: 32
    #     height: 32
    to_tensor:
      params: ~
  target_transforms: ~
