# Dataloader
batch_size: 1
num_workers: 4
drop_last: True
# Dataset
dataset:
  name: "sunrgbd"
  params:
    root: "data/sunrgbd_trainval"
    split: "train"
  transforms:
    to_tensor:
      params: ~
  depth_transforms:
    to_tensor:
      params: ~
  target_transforms:
    to_tensor:
      params: ~
