train:
  experiment_name: "mae"
  # Runner
  num_epochs: 15
  max_iter: ~
  log_iter: ~
  eval_iter: ~
  runner_name: mae
  distributed: False
  device: cuda

  # Dataloader
  batch_size: 128
  num_workers: 4
  drop_last: True

  # Hyperparameter
  mask_ratio: 0.5
  accum_iter: 4
  warmup_epochs: 40
  lr: 1e-03
  min_lr: 1e-04

  # Model
  model:
    name: "mae_vit_large_patch16"
    params:
      norm_pix_loss: True
  # Dataset
  dataset:
    name: "nyuv2"
    params:
      root: "data/NYUDepthv2"
      split: "train"
    transforms:
      RandomResizedCrop:
        params:
          size: [224, 224]
          scale: [0.2, 1.0]
          interp_mode: 3
      RandomHorizontalFlip:
        params: ~
      to_tensor:
        params: ~
      normalize:
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    target_transforms:
      resize:
        params:
          size: [224, 224]

  # Losses
  losses:
    ~
    # loss:
    #   type: native_scaler
    #   weight: 1.0
    #   params: ~

  # Optimizer
  opt_params:
    lr_default: 1e-3
    wd_default: 1e-4
    betas: (0.9, 0.95)
    momentum: ~
    lr_list: ~
    group_keys: ~
    wd_list: ~

  opt_name: "adamw"
  scheduler_name: "constant"
  # Logger
  use_tensorboard: True
  tensorboard_folder:
  log_dir: log
  output_dir: output_dir/
  model_folder: ~

val:
  # Dataset
  dataset: ~
test:
  need_test: False
